utility_agents:
  - agent_class: SearchAgent
    agent_name: "Banking Assistant"
    agent_description: 
      Banking Assistant can search the Web for relevant banking information.
    config:
      output_style: "conversational"
      contexts:
        - "chat_history"

orchestrator:
  agent_list:
    - agent_name: "Banking Assistant"
  rai_config:
    - name: "financial advice" # Required. Unique identifier for the rule.
      description: "Reject queries that ask investment or financial advice." # Required. Explanation of the policy.
      weight: 1.0 # Required. Importance level of this rule (0.0–1.0).
      passing_examples: # Required. Include at least one query that complies with this rule.
        - "Tell me how to open an account"
        - "What is a credit card balance?"
        - "What do you know about interest rates?"
      failing_examples: # Required. Include at least one query that violate this rule.
        - "Should I invest in stocks or bonds?"
        - "What's the best way to save for retirement?"
        - "Current stock market trends and predictions?"
    